apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: spring-petclinic

  ports:
    - name: web
      port: 80
      targetPort: 8181
      protocol: TCP
