apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
        - name: spring-petclinic
          image: st251/petclinic:58
          ports:
            - name: web
              containerPort: 8181
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: mysql
            - name: DB_URL
              value: jdbc:mysql://db.c5sjapmrqkcl.us-east-1.rds.amazonaws.com:3306/petclinic








